# Generated by Django 6.0 on 2025-12-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_candidate_cgpa_candidate_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='linkedin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
