# Generated by Django 6.0 on 2025-12-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_alter_candidate_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
